const PRODUCTS = [
  {id:1,name:"Porsche GT3 RS Wall Poster — Premium Car Decor",category:"Supercars",price:89,oldPrice:159,tag:"LIMITED",desc:"Upgrade your room with the Ultimate Supercar Collection!.",image:"https://github.com/wolfr4h6900-sketch/gearvault-store/blob/main/ChatGPT%20Image%20Sep%2023,%202026,%2003_58_12%20PM.png?raw=true"},
  {id:2,name:"MERCEDES-AMG GT BLACK SERIES Poster — Premium Car Decor",category:"Supercars",price:89,oldPrice:159,tag:"NEW",desc:"The ultimate expression of performance, built for those who demand more.",image:"https://github.com/wolfr4h6900-sketch/gearvault-store/blob/main/ChatGPT%20Image%20Sep%2023,%202026,%2003_58_17%20PM.png?raw=true"},
  {id:3,name:"🏎️ Pagani Huayra R Evo — Premium Car Wall Poster",category:"Supercars",price:99,oldPrice:199,tag:"LIMITED",desc:"Turn your wall into a hypercar showcase. The Pagani Huayra R Evo poster features an aggressive race-inspired design, carbon-fibre styling, premium typography, and a clean technical layout—perfect for anyone who lives and breathes cars.",image:"https://github.com/wolfr4h6900-sketch/gearvault-store/blob/main/ChatGPT%20Image%20Sep%2023,%202026,%2003_58_00%20PM.png?raw=true"},
  {id:4,name:"🏁 McLaren P1 — Premium Car Wall Poster",category:"Supercars",price:99,oldPrice:199,tag:"LIMITED",desc:"The McLaren P1 represents McLaren’s pursuit of extreme performance, advanced aerodynamics, and futuristic automotive engineering. This poster features the iconic black McLaren P1 in a dramatic studio-style presentation, complemented by bold P1 typography and a clean performance-spec layout.",image:"https://github.com/wolfr4h6900-sketch/gearvault-store/blob/main/ChatGPT%20Image%20Sep%2023,%202026,%2004_02_50%20PM.png?raw=true"},
  {id:5,name:"BMW M4 Coupé",category:"BMW",price:89,oldPrice:159,tag:"RARE",desc:"The BMW M4 Coupé combines breathtaking performance with everyday usability. With its distinctive design, advanced technology, and motorsport DNA, it delivers an unforgettable driving experience—on the road and on the track.",image:"https://github.com/wolfr4h6900-sketch/gearvault-store/blob/main/ChatGPT%20Image%20Sep%2023,%202026,%2004_02_56%20PM.png?raw=true"},
  {id:6,name:"NISSAN GT-R NISMO",category:"JDM",price:89,oldPrice:159,tag:"POPULAR",desc:"A street legend for your collection.",image:"https://github.com/wolfr4h6900-sketch/gearvault-store/blob/main/ChatGPT%20Image%20Sep%2023,%202026,%2003_58_22%20PM.png?raw=true"},
  {id:7,name:"FERRARI 812 SUPERFAST",category:"Supercars",price:99,oldPrice:159,tag:"BESTSELLER",desc:"The Ferrari 812 Superfast is a masterpiece of Italian engineering, delivering unparalleled performance and design.",image:"https://github.com/wolfr4h6900-sketch/gearvault-store/blob/main/ChatGPT%20Image%20Sep%2023,%202026,%2004_02_53%20PM.png?raw=true"},
  {id:8,name:"BMW M8-M Power / Ultimate Driving Machine",category:"BMW",price:89,oldPrice:149,tag:"NEW",desc:"German performance with a dark aesthetic.",image:"https://github.com/wolfr4h6900-sketch/gearvault-store/blob/main/ChatGPT%20Image%20Sep%2023,%202026,%2004_02_27%20PM.png?raw=true"},
  {id:9,name:"Performance Edition — 27-Piece Wall Poster Set",category:"COMBO",price:499,oldPrice:899,tag:"COMBO",desc:"A collection of high-quality wall posters featuring some of the most iconic cars in supercar history.",image:"https://github.com/wolfr4h6900-sketch/gearvault-store/blob/main/Screenshot%202026-09-22%20225127.png?raw=true"},
  {id:10,name:"Levi Ackerman — Split Poster Set",category:"Anime",price:359,oldPrice:499,tag:"NEW",desc:"Bring Levi Ackerman's sharp, fearless energy to your wall with this striking split-panel anime poster set. The two coordinated prints create one powerful action composition, while the premium 300 GSM finish keeps every bold detail crisp. Each 12 × 18 inch poster comes ready with double-sided tape for an easy, clean display.",image:"assets/anime-levi-poster.jpg",images:["assets/anime-levi-poster.jpg","assets/anime-details.png"]}
];

function getProduct(id){ return PRODUCTS.find(p => p.id === Number(id)); }
function money(n){ return "₹" + Number(n).toLocaleString("en-IN"); }